### ISSUE TITLE
Picker position (preview) not updated after save & publishing image (refresh needed)

### ISSUE THREAD

**Issue by micschk** [jonom/silverstripe-focuspoint#100]
When a user changes the position of the focuspoint in the CMS fileSelectForm modal and then publishes the file, the UI returns to read-only mode (greyed & dimmed preview). But at this point the FP picker's position is not updated to reflect the new value (remains at its previous position). 

Upon closing & reopening this modal, the picker does reflect the new FP position (so the new value gets saved correctly). Probably something to do with the "graphql context not being updated" or so...

**Comment by jonom** [comment]
@micschk do you know if the same thing happens to other fields? Like if you change the title, is that immediately reflected in the read-only form? Just wondering if this is something that should be fixed in this module, or core.

**Comment by jonom** [comment]
I know I see `DRAFT` badges all the time on things in Silverstripe that I know are published so it wouldn't be the first time something didn't get updated immediately 😅

**Comment by jonom** [comment]
Happy to report that this doesn't happen in SS5, so closing this.

**Comment by palomamtnez** [comment]
Hi @jonom  :) 

I have just installed this package on my SS5 site. When I try to modify the focal point of my image, the picker position doesn't move. I tried to click on a corner just to see if the focal point works without the picker moving, but when I render my image via $FocusFill, it still crops it as regular. Do you have any idea why this might happen?


<img width="492" alt="Screen Shot 2023-08-23 at 4 47 32 PM" src="https://github.com/jonom/silverstripe-focuspoint/assets/13962572/05b1f362-6e97-4cdd-9d69-2c862ed3d0fb">
