### ISSUE TITLE
Y axis inverted between SSv3 and v4 version of module (between module v2 and v3/4)

### ISSUE THREAD

**Issue by micschk** [jonom/silverstripe-focuspoint#102]
Upon updating a project from Silverstripe 3 to 4 (yeah I know) all focuspoints seemed a bit off vertically. It only now occurred to me that the Y axis has been [swapped](#66 ) not just in the [UI element](https://github.com/jonom/silverstripe-focuspoint/blob/88d8b2d5c356591809de5f8cb00fd2334595e855/client/src/components/FocusPointPicker.jsx#L26) but altogether in the whole module (which is good, otherwise it'd be a bug).

So the axis is not necessarily wrong I'd say but it is indeed inverted. But this could use some kind of migration task to migrate the existing focuspoint values between silverstripe 3 & 4. PR coming up...

**Comment by jonom** [comment]
This is supposed to take care of that but maybe it got broken at some point? https://github.com/jonom/silverstripe-focuspoint/blob/master/src/Dev/FocusPointMigrationTask.php

**Comment by micschk** [comment]
My bad! And no it's not broken, just runs out of memory every ~100 images locally. Have about 100.000 images to update so took a look at this migrationtask and thought it just updated the table columns; didn't notice the line inverting its value...

I'll just have to run the migration script lot's of times then...

**Comment by micschk** [comment]
OK, so this whole issue is not an issue at all. Migrationtask is running just fine and within seconds. Nevermind...
