### ISSUE TITLE
Backend interface not functioning

### ISSUE THREAD

**Issue by torindul** [jonom/silverstripe-focuspoint#13]
Hi, I can't get the backend focal point selector to function, the changes all appear on the site once the module has been installed, but all that appears on the image info is the area to select the focal point and a blank text box. Nothing happens once a focal point has been selected. 

Any tips? - It would be great to put your work to use on this specific client project.

Thanks,
George.

**Comment by jonom** [comment]
Hi George, if you give the readme file another quick read you should see a
note about having to flush the templates after installation (I might need
to make this a bit clearer). You can't flush templates from the database
build screen prior to the most recent versions of SilverStripe, you need to
flush from the CMS or a page on your website.. Let me know if that doesn't
fix your issue ;)

**Comment by torindul** [comment]
HEy Jonom,

Thanks for the quick response.

I've removed, and reinstalled the module and made sure I fully followed the instructions. Still the same result. As far as I can see, in SilverStripe 3.1.10, the new template files appear fine. I see the image and a text box, with a comma.

Nevertheless, hovering the image shows no change, and clicking it doesn't make a change either... What is supposed to happen? - Is that text box's value supposed to alter?

See my attached screenshots, one of the image within the Edit option of the FileUpload field, the other within the Files CMS tab.

Your help is appreciated :-)

![screen shot 2015-03-22 at 17 01 43](https://cloud.githubusercontent.com/assets/3453296/6770348/6c267d4c-d0b5-11e4-978a-135defe1cf8c.png)
![screen shot 2015-03-22 at 17 01 56](https://cloud.githubusercontent.com/assets/3453296/6770349/6c44485e-d0b5-11e4-8a80-3ba9e4d3fe25.png)

**Comment by jonom** [comment]
You probably already tried this but can you just visit your
site.dev/admin?flush=1 and see if that fixes it?

**Comment by torindul** [comment]
Already tried that to no avail, you can see I even flushed the templates in one of the URLs on the screenshots. Any ideas? - It's been like this on one or two sites I've run.. Do you have any requirements for any PHP modules outside of the core SilverStripe requirements?

**Comment by jonom** [comment]
Can you delete your cache folder or create a silverstripe-cache folder and
see if that helps? After that I would load up the network inspector in your
browser and see if any scripts or css is failing to load

**Comment by jonom** [comment]
p.s. there aren't any other module requirements for this.

It looks like the javascript and/or CSS isn't loading in the CMS. It could be either that it's attempting to load them but it's not working (wrong path or permissions issue) or that it's not trying to load them at all - but that seems improbable.

I would guess it's a path issue - is the module installed in a folder named 'focuspoint' at the root of the site?

Can you please report back anything you work out so I can fix or make a note for future users.

**Comment by torindul** [comment]
Okay, that was all it was. It was a simple case of naming the directory 'focuspoint', which, when downloaded from github is known as silverstripe-focuspoint-1.x (which i then named silverstripe-focuspoint). Renaming to focuspoint on its own solved this.

All seems to be working now, I'll have a play around. Maybe make it clear you need it named that way in the Read Me :) -- Or use relative paths for inclusion. 

I'll mark this as closed now :+1:

**Comment by jonom** [comment]
ReadMe updated. Have a good one
