### ISSUE TITLE
Crop Reference Point Defaults

### ISSUE THREAD

**Issue by clintLandrum** [jonom/silverstripe-focuspoint#14]
Setting 'FocusY' => '1' at https://github.com/jonom/silverstripe-focuspoint/blob/1.x/code/FocusPointImage.php#L13 doesn't seem to work. Even onBeforeWrite isn't catching it after adjusting these points and re-saving.
This could also be overwritten in YAML (much better choice I understand) but I'm just experimenting currently and not getting this to work.

**Comment by jonom** [comment]
I think the default would only apply on creation of a new Image - i.e. when you upload one. Perhaps also when you install the module for the first time and build the database. Also note that if you change this value you'll have to flush SilverStripe's config cache before it will be recognised (add ?flush to a URL). If you set the default to 1, then flush the cache, then upload a new image, does it then do what you expect?

**Comment by clintLandrum** [comment]
Sorry for the delay. Yes, you were correct on everything here. Thanks and nice work on the module.
