### ISSUE TITLE
BUG: dash in generated filename breaks filename lookups

### ISSUE THREAD

**Issue by mikeyc7m** [jonom/silverstripe-focuspoint#16]
FocusPoint is adding a dash to the filename. This breaks the Silverstripe convention of prepending resampling information using just alphanumerics and ending with a dash. Silverstripe's File::find() expects the dash to denote the start of the original filename. It's also breaking the SecureAssets component, which returns 404 on all focuspoint images. 

The problem code appears to be line 113 in FocusPointImage.php:
`$focusHash = $this->PercentageX() . '-' . $this->PercentageY();`

Just remove the dash and it seems to work fine.

**Comment by jonom** [comment]
Hi @mikeyc7m I'm pretty sure this issue doesn't exist in my local development branch as I've changed the file name stuff quite a bit, but I'll leave this open as a reminder for myself to check before I release the next version. Will be doing some updates soon (famous last words) for SS 3.2 release.

**Comment by jonom** [comment]
@mikeyc7m I don't think this is an issue anymore so I'm closing - but feel free to re-open if I'm wrong
