### ISSUE TITLE
Module doesn't work with ImagickBackend

### ISSUE THREAD

**Issue by bummzack** [jonom/silverstripe-focuspoint#24]
When using the `ImagickBackend` instead of the `GDBackend` for image manipulation, the module crashes because `ImagickBackend` lacks the `crop` method.

Not entirely sure if this should be fixed in SilverStripe core instead (eg. extending the `Image_Backend` interface with some additional methods, such as `crop` and also implement them in the `ImagickBackend`)?

**Comment by jonom** [comment]
Sorry for the delay @bummzack I was taking some time off.

Huh! Yes I think that the [Image_Backend](http://api.silverstripe.org/3.3/class-Image_Backend.html) interface ideally needs a `crop($top, $left, $width, $height)` method added as does [ImagickBackend](http://api.silverstripe.org/3.3/class-ImagickBackend.html).

Adding a new method to an interface would be a breaking change but we could add a crop method to `ImagickBackend` in the 3 branch as a short term thing. I know @tractorcow was looking at dropping the ImageBackend interface for SS4 and using a third party image manipulation API instead so it may be redundant to implement a fuller solution in 4, but I don't know if that has progressed.

@bummzack Do you want to open a PR on framework (3 branch) for adding a crop method to ImagickBackend? Alternatively if you want to add an extension to this module for ImagickBackend that achieves the same end I'll be happy to accept it.
