### ISSUE TITLE
Cropper-addon

### ISSUE THREAD

**Issue by micschk** [jonom/silverstripe-focuspoint#25]
Hi Jonom, 

Thanks for your excellent modules! I've just published an a module that adds cropping to your FocusPoint module: https://github.com/micschk/silverstripe-focuspointcropper/

**Comment by jonom** [comment]
@micschk sorry I never got around to trying this out 😬 if you ever [upgrade for SS4](https://github.com/micschk/silverstripe-focuspointcropper/issues/8) I'll be happy to reference this in the ReadMe.
