### ISSUE TITLE
Php -warning with Image:CropWidth()

### ISSUE THREAD

**Issue by joelgrondrup** [jonom/silverstripe-focuspoint#32]
[Warning] Missing argument 1 for Image::CropWidth(), called ../public/framework/view/ViewableData.php on line 446 and defined

**Comment by jonom** [comment]
Hi Joel, would need a lot more information from you to do anything about this. Feel free to amend and re-open issue if you like.

**Comment by joelgrondrup** [comment]
Hi Jonom. 

First of all. I was in a hurry and didn't get a chance to thank you for this awesome module. 

I'm getting this error:

[Warning] imagealphablending() expects parameter 1 to be resource, boolean given ../public/framework/filesystem/GD.php:184 

imagealphablending(,) 
GD.php:184
GDBackend->croppedResize(,1277) 
Image.php:299
Image->generateFill(GDBackend,,1277) 
call_user_func_array(Array,Array) 
Image.php:764
Image->generateFormattedImage(Fill,,1277) 
call_user_func_array(Array,Array) 
Image.php:696
Image->getFormattedImage(Fill,,1277) 
Image.php:286
Image->Fill(,1277) 
Image.php:451
Image->CropWidth() 
ViewableData.php:421
ViewableData->obj(CropWidth,,,1) 
ViewableData.php:494
ViewableData->XML_val(CropWidth,,1) 
call_user_func_array(Array,Array) 
SSViewer.php:179
SSViewer_Scope->__call(XML_val,Array) 
SSViewer.php:550
SSViewer_DataPresenter->__call(XML_val,Array) 
.cache.form-extras.templates.forms.CropboxField.ss:13
SSViewer_DataPresenter->XML_val(CropWidth,,1) 
.cache.form-extras.templates.forms.CropboxField.ss:13
include(/srv/users/serverpilot/apps/mashsteak-com/public/silverstripe-cache/serverpilot/.cache.form-extras.templates.forms.CropboxField.ss) 
SSViewer.php:1064
SSViewer->includeGeneratedTemplate(/srv/users/serverpilot/apps/mashsteak-com/public/silverstripe-cache/serverpilot/.cache.form-extras.templates.forms.CropboxField.ss,CropboxField,,Array,) 
SSViewer.php:1126
SSViewer->process(CropboxField,) 
ViewableData.php:360
ViewableData->renderWith(Array) 
FormField.php:842
FormField->Field(Array) 
CropboxField.php:117
CropboxField->Field() 
ViewableData.php:421
ViewableData->obj(Field,,,1) 
ViewableData.php:494
ViewableData->XML_val(Field,,1) 
call_user_func_array(Array,Array) 
SSViewer.php:179
SSViewer_Scope->__call(XML_val,Array) 
SSViewer.php:550
SSViewer_DataPresenter->__call(XML_val,Array) 
.cache.framework.templates.forms.FormField_holder.ss:31
SSViewer_DataPresenter->XML_val(Field,,1) 
.cache.framework.templates.forms.FormField_holder.ss:31
include(/srv/users/serverpilot/apps/mashsteak-com/public/silverstripe-cache/serverpilot/.cache.framework.templates.forms.FormField_holder.ss) 
SSViewer.php:1064
SSViewer->includeGeneratedTemplate(/srv/users/serverpilot/apps/mashsteak-com/public/silverstripe-cache/serverpilot/.cache.framework.templates.forms.FormField_holder.ss,CropboxField,,Array,) 
SSViewer.php:1126
SSViewer->process(CropboxField,) 
ViewableData.php:360
ViewableData->renderWith(Array) 
FormField.php:865
FormField->FieldHolder() 
ViewableData.php:421
ViewableData->obj(FieldHolder,,,1) 
ViewableData.php:494
ViewableData->XML_val(FieldHolder,,1) 
call_user_func_array(Array,Array) 
SSViewer.php:179
SSViewer_Scope->__call(XML_val,Array) 
SSViewer.php:550
SSViewer_DataPresenter->__call(XML_val,Array) 
.cache.framework.templates.Includes.Form.ss:63
SSViewer_DataPresenter->XML_val(FieldHolder,,1) 
.cache.framework.templates.Includes.Form.ss:63
include(/srv/users/serverpilot/apps/mashsteak-com/public/silverstripe-cache/serverpilot/.cache.framework.templates.Includes.Form.ss) 
SSViewer.php:1064
SSViewer->includeGeneratedTemplate(/srv/users/serverpilot/apps/mashsteak-com/public/silverstripe-cache/serverpilot/.cache.framework.templates.Includes.Form.ss,Form,,Array,) 
SSViewer.php:1126
SSViewer->process(Form,) 
ViewableData.php:360
ViewableData->renderWith(Array) 
Form.php:1550
Form->forTemplate() 
ViewableData.php:495
ViewableData->XML_val(Form,,1) 
call_user_func_array(Array,Array) 
SSViewer.php:179
SSViewer_Scope->__call(XML_val,Array) 
SSViewer.php:550
SSViewer_DataPresenter->__call(XML_val,Array) 
.cache.framework.templates.UploadField_FileEdit.ss:15
SSViewer_DataPresenter->XML_val(Form,,1) 
.cache.framework.templates.UploadField_FileEdit.ss:15
include(/srv/users/serverpilot/apps/mashsteak-com/public/silverstripe-cache/serverpilot/.cache.framework.templates.UploadField_FileEdit.ss) 
SSViewer.php:1064
SSViewer->includeGeneratedTemplate(/srv/users/serverpilot/apps/mashsteak-com/public/silverstripe-cache/serverpilot/.cache.framework.templates.UploadField_FileEdit.ss,ViewableData_Customised,,Array,) 
SSViewer.php:1126
SSViewer->process(ViewableData_Customised,) 
ViewableData.php:360
ViewableData->renderWith(UploadField_FileEdit) 
UploadField.php:1429
UploadField_ItemHandler->edit(SS_HTTPRequest) 
RequestHandler.php:288
RequestHandler->handleAction(SS_HTTPRequest,edit) 
RequestHandler.php:200
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
GridFieldDetailForm.php:102
GridFieldDetailForm->handleItem(GridField,SS_HTTPRequest) 
GridField.php:978
GridField->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:158
Controller->handleRequest(SS_HTTPRequest,DataModel) 
LeftAndMain.php:451
LeftAndMain->handleRequest(SS_HTTPRequest,DataModel) 
AdminRootController.php:92
AdminRootController->handleRequest(SS_HTTPRequest,DataModel) 
Director.php:385
Director::handleRequest(SS_HTTPRequest,Session,DataModel) 
Director.php:149
Director::direct(/admin/destinations/Destination/EditForm/field/Destination/item/1/ItemEditForm/field/Image/item/5/edit,DataModel) 
main.php:188

**Comment by jonom** [comment]
What does your `CropboxField.ss` template look like? Does this error persist if you remove the FocusPoint module?

**Comment by jonom** [comment]
I don't think this is an issue with FocusPoint but maybe a conflict from this class: https://github.com/lekoala/silverstripe-form-extras/blob/master/code/fields/CropboxField.php

Since SS 3.2 `Image` has a [CropWidth method](http://api.silverstripe.org/3.2/class-Image.html#_CropWidth) so adding a property with the same name through an extension is not going to work.
