### ISSUE TITLE
Focus point is not saved on live server.

### ISSUE THREAD

**Issue by Martindoorneakamp** [jonom/silverstripe-focuspoint#38]
First off, thanks for the module, i like it alot.
But something strange is going on, i just moved a website to the live server, and de focuspoint plugin does not seem to work. I'm getting no errors whats so ever but each time i pick a focus point and save, the focus point gets resetted. The weird thing is that it works on our local server. And other projects on the save live server do not have the same problem.
 Im using silverstripe 3.5.0.

**Comment by jonom** [comment]
Maybe related to #34?

Are you using any other modules that extend or modify the Image class?

It's odd that it's working locally... I trust you ran a dev/build on live DB to add the FocusX and FocusY fields to Image?

**Comment by Martindoorneakamp** [comment]
Thanks for your reply. The weird thing is that the values are getting saved in the db. But somehow don't seem to work form both the preview version in the cms, as for the frontend. I'm going to to try a fresh install, but like i said it works on the local sever. I have used the pluggin for over 10 sites, and this never happend.. The only difference that i can think off is that on the local server all the tables are forced to lowercase (MAMP on windows), and on the live server they are have a uppercase starting letter.

**Comment by jonom** [comment]
Ah, does sound like the same issue as #34 then.
