### ISSUE TITLE
Image src(unknown) in backend & field not appearing

### ISSUE THREAD

**Issue by KINKCreative** [jonom/silverstripe-focuspoint#40]
I have a pretty new site - and for some reason I am not seeing the FocusPoint field appearing in the admin.

https://www.dropbox.com/s/ifwg9g6zrho3b87/Screenshot%202017-02-10%2013.20.17.png?dl=0

I have tried various SS versions, updating the module - so I'm not sure -- I may be missing sometihng.

**Comment by jonom** [comment]
Sorry have been away, did you sort this out?
