### ISSUE TITLE
Not Compatible with Silverstripe 4

### ISSUE THREAD

**Issue by tungdt-90** [jonom/silverstripe-focuspoint#41]
Hi, 

I want to ask, is there any chance that this module can be used in Silverstripe 4 ? I use this module a lot and would like to continue using it in the next release of Silverstripe.

**Comment by jonom** [comment]
I will definitely aim to upgrade this for SS4 at some point. If anyone wants to do the work and open a pull request before I do, please feel free :)

**Comment by pitchandtone** [comment]
@jonom could you provide a cost to get it upgraded? I have a motivated client.

**Comment by jonom** [comment]
@pitchandtone can you send me an email please and we can discuss - jonomenz@gmail.com

**Comment by sminnee** [comment]
...now that beta1 is out you shouldn't be chasing a moving target any more ;-)

**Comment by hoodweb** [comment]
Is there any news regarding ss4 compatibility?

**Comment by jonom** [comment]
@hoodweb no news, when I can justify the time on a project I'll certainly get it done but there is no timeline. It should be pretty straightforward to upgrade so if you need it upgraded soon please feel free to open a pull request for SS4 compatibility and I will review promptly. You're also welcome to contact me if you want to sponsor the work.

**Comment by hoodweb** [comment]
@jonom I believe it could be complicated due to the upload field being React now? I'll maybe look at it, if a project comes up with time to spare.

**Comment by jonom** [comment]
> I believe it could be complicated due to the upload field being React now?

True! I haven't looked in to it yet but hopefully it won't be too much of a hurdle.

**Comment by jonom** [comment]
I was curious about this so had a look. The good news is that the fields in the file detail form are still built with good old fashioned PHP. Unfortunately it's custom built rather than relying on `getCMSFields()`... not sure what the reasoning was for that but it's not really a problem. We should be able to hook in to `SilverStripe\AssetAdmin\Forms\AssetFormFactory::getFormFields` with the `updateFormFields()` extension hook to modify the file editing form.

I'm thinking it might be good to upgrade the large preview image area to turn it in to a nice big FocusPoint field. The click-to-zoom feature is redundant as there is a separate always-visible zoom button, and it would save space compared to rendering the image twice. Could maybe have a very subtle indication of the focuspoint by default so you can appreciate the details of the image, but when you hover over the image you get the regular cloudy/radial-gradient interface and can click to change it.

**Comment by youpixxl** [comment]
Hi and thanks for your great work :-)
Did you make progress on ss4 upgrade ?

**Comment by jonom** [comment]
@youpixxl It will probably be months before I can work on this in my spare time unfortunately. I have a toddler now and don't have a lot of spare time to give to open source work anymore. I will promptly review pull requests though, so please feel free to do the upgrade yourself! I'm also happy to talk to anyone who wants to sponsor me to do the upgrade work (contact me directly to discuss).

**Comment by bummzack** [comment]
@jonom I know how you feel, I'm in a similar situation. I used this module a lot in SS3 and I really wish there was a version for SS4. Did the offer from @pitchandtone not work out?

**Comment by pitchandtone** [comment]
The project we were going to use it on didn’t go ahead in the end. No doubt this will get used at some point in 2018 though.

**Comment by bummzack** [comment]
I have started working on a SS4 update of this. 
@jonom Are you happy with the namespace `Jonom\FocusPoint`? You should also branch the current `master` as `2`, so that further development on the 2.x release line can go into `2`. When I'm ready with my PR, I'm going to create it against `master`… this seems to be in line with how it's being done in SS core modules. I hope that's alright with you.

**Comment by jonom** [comment]
@bummzack I apologise, I should have left a message here - I started upgrading this module last week, after Joel Grondrup kindly pitched in some development budget to get the ball rolling. The heavy lifting is mostly done and I'll post a dev branch shortly you can try out.

**Comment by bummzack** [comment]
@jonom Oh, good to hear. I guess you're also waiting for this to get resolved then: https://github.com/silverstripe/silverstripe-asset-admin/issues/718. Or how are you doing the react integration?

**Comment by bummzack** [comment]
I also considered replacing the `FocusX` and `FocusY` fields on Image with a `DBComposite` field. 

So the basic extension would no longer do:
```
private static $db = [
    'FocusX' => 'Double',
    'FocusY' => 'Double'
];
```

but rather:
```
private static $db = [
    'FocusPoint' => 'FocusPoint'
];
```

It would open up future enhancements where you might even have multiple focus-points on one object. But I guess this is not the proper place for this… I could open a separate issue though if you like.

**Comment by jonom** [comment]
> Or how are you doing the react integration?

I couldn't find any examples or docs or information at all about customising React elements in SS4, so I'm still using entwine. I had to hook in to the redux store to get the field changes recognised but apart from it's pretty much ignoring React currently.

> I also considered replacing the FocusX and FocusY fields on Image with a DBComposite field.

Sure, open an issue if you like :) I'm not sure if it would be of major benefit though, so might be more trouble than it's worth?

**Comment by bummzack** [comment]
Yeah, documentation is scarce. This one is pretty much all there is: https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/reactjs_redux_and_graphql/

I _really_ wonder how you integrate this with entwine though? Asset-Admin is 100% react, and the uploadfield component uses react as well. I guess I'll see when you publish your branch :)

The main reason for a single field for both properties would be that it directly maps to a FormField. So scaffolding would work properly and it's also easier to build the react integration.

**Comment by jonom** [comment]
Thanks for those docs, I'll take a look.

> I really wonder how you integrate this with entwine though? Asset-Admin is 100% react, and the uploadfield component uses react as well. I guess I'll see when you publish your branch :)

The extra fields are added through PHP, then styled and entwine behaviour added with LeftAndMain extra requirements. You can access the redux store from anywhere with `window.ss.store` so I'm updating the form state by dispatching an action from the entwine code.

**Comment by jonom** [comment]
Okay, I've pushed a new branch. Anyone wanting to test this can install with

```
composer require jonom/focuspoint:dev-ss4-upgrade
```

Let me know how you go!

**Known issues:**
* When working with images in the CMS outside of the Files section (e.g. HTMLEditorField insert), the editing form is disabled for some reason. I assume maybe this will be restored at some point? Currently the FocusPoint field is still active in that context, but you can't save the changes. This is a very bad experience for the user so FocusPoint field probably needs a read only or disabled option added.
* Not sure image chaining is working as well as it did before but I doubt this is used very much
* Tests still need to be updated

**Comment by bummzack** [comment]
Awesome, thanks for your work on this. Just installed it and will give it a try.
Regarding unit-tests, I was able to make them work. Feel free to copy/modify from my repo: https://github.com/bummzack/silverstripe-focuspoint/tree/wip/ss4/tests

**Comment by jonom** [comment]
Sweet, thanks for that! I have updated the tests in the dev branch.

**Comment by jonom** [comment]
@bummzack what do you think about the state of the dev branch? I'm certainly open to your idea about using a composite DB field and integrating with the react layer 'properly' rather than tacking on the functionality like I have. If you want to explore that I'll hold off on merging/releasing for now.

**Comment by bummzack** [comment]
@jonom It works better than I expected, I never thought that tacking something onto a react app with entwine would work :)
The change from entwine to react could also happen in a minor release, but for the shift from two individual fields to a composite field it would require a major version change. So this might be something worth considering doing before releasing the SS4 version.

Benefits I could see from that change:
 - Field scaffolding
 - An image could potentially have multiple focus-points
 - ???
 - Profit!

**Comment by bummzack** [comment]
Not sure if something like this would work too:

```php
private static $many_many = [
    'Images' => Image::class
];

private static $many_many_extraFields = [
    'Images' => [ 'ExtraFocusPoint' => 'FocusPoint' ]
];
```

So that you could attach an image to multiple DataSources and set the focus point on the relation. For the rare use case where you want the same image but different focus-points on different pages.

**Comment by bummzack** [comment]
@jonom I'll give this a try, if you don't mind (eg. implement the focus coordinates as a composite field).

**Comment by jonom** [comment]
Sure :) just keep in mind upgrading, would need a script to migrate from the old schema. Ideally this would happen automatically.

**Comment by pitchandtone** [comment]
https://github.com/dnadesign/silverstripe-migraterelations might be of use if you’ve changed the DB structure.

**Comment by bummzack** [comment]
@pitchandtone Nice, thanks for the tip. I'll look into that but I guess it's not going to be *that* complicated to warrant requiring another module. I'm pretty much done with changing to a composite DB-field and will finish tomorrow.

**Comment by jonom** [comment]
Latest version with @bummzack's work included has been tagged **3.0.0-beta.1** if anybody wants to give it a whirl.

**Comment by gorriecoe** [comment]
Initial tests look good.  Only a minor observation mention in #51

**Comment by youpixxl** [comment]
Hi !
I have implemented the upgrade and it works great. Again thanks a lot for your hard work !

**Comment by jonom** [comment]
3.0.0 release has been tagged
