### ISSUE TITLE
PHP7.1

### ISSUE THREAD

**Issue by lerni** [jonom/silverstripe-focuspoint#42]
CroppedFocusedImage with focuspoint 2.4.* and SilverStripe 3.6.*@dev on PHP 7.1.3 throws a [Notice] like: A non well formed numeric value encountered. This happens on line 285@FocusPointImage.php

	$widthRatio = $this->owner->width / $width;

A possible fix is to sanitize parameters like:

	$width = intval($width);
	$height = intval($height);

Probable other methods need this too. Would you accept a PR with the above fix? See also https://github.com/silverstripe/silverstripe-framework/commit/ae0fe75fba35918735656ea82cab2e7584b27f07

**Comment by jonom** [comment]
Thanks @lerni. How do you encounter this error? Do you need to pass in a weird argument like `$FocusFill(100, 'twenty')`?

**Comment by lerni** [comment]
@jonom you are right! Somehow a '$' after width made it into template and than the Notice started to appear with PHP >= 7 but didn't with 5.6
