### ISSUE TITLE
Disabled picker obvious ss4

### ISSUE THREAD

**Issue by gorriecoe** [jonom/silverstripe-focuspoint#51]
The picker needs to be more obvious when disabled on ss4.  Perhaps a different pointer icon.

**Comment by bummzack** [comment]
You mean that the disabled state should be more obvious? Eg. a distinct difference between enabled and disabled?

**Comment by gorriecoe** [comment]
Sorry yes that is what I mean.  Below is a screen shot of the disabled state.
![screenshot-2018-1-31 silverstripe - edit page](https://user-images.githubusercontent.com/11811440/35594415-f7e92500-0677-11e8-8e70-be09c06cf198.png)

**Comment by jonom** [comment]
Maybe we leave the crosshairs but put a grey 🔒 or 🚫 in the corner.

The focus point should also not change when the image is clicked if the field is disabled / read-only.

**Comment by micschk** [comment]
2021 version: https://github.com/jonom/silverstripe-focuspoint/issues/99
