### ISSUE TITLE
Focus point broken when viewing file outside of asset admin

### ISSUE THREAD

**Issue by zanderwar** [jonom/silverstripe-focuspoint#52]
The javascript hasn't been included in all locations where focuspoint appears by default. The "file selector" dialog on an `UploadField` is missing this functionality, the FocusPointField appears, but you cannot alter the x,y position.

Lead's to a tedious double handling scenario

#ss4

**Comment by bummzack** [comment]
Not a bug, this is by design. You can't save files in the insert-file dialog, so you won't be able to store the changed coordinates. All other files are read-only as well. Probably also related to #51 

I guess a nicer solution would be if you could open/edit the focus-point directly on the upload-field without having to open the insert-file dialog.

**Comment by zanderwar** [comment]
What about an ajax solution? You can disable the buttons while the request is active? Calling it a PITA would be going gentle on it as appreciative as I remain for being able to do it in the first place

**Comment by bummzack** [comment]
Can you elaborate what you mean? You mean saving the focus-point as soon as it has been altered? I think that would be pretty bad UX wise, as you usually do your changes and confirm them by saving (same behavior as in asset-admin).

The insert file dialog isn't meant to be used for modifying file properties at all. I don't think it would be wise to enable editing there. Maybe the focus-point field should be removed entirely there and be accessible via other means (for example via an additional button on the UploadField itself).

**Comment by zanderwar** [comment]
I just consider a scenario like my own where the folders that these files belong in live alongside 30,000 other images. So uploading a file, saving and then having to go to asset admin and find the file is just excruciating.

**Comment by jonom** [comment]
Hi @zanderwar this is a known issue but I hadn't documented it well. See https://github.com/jonom/silverstripe-focuspoint/issues/53
