### ISSUE TITLE
Template won't output FocusFillMax Links

### ISSUE THREAD

**Issue by pxwee5** [jonom/silverstripe-focuspoint#55]
```
$Image.FocusFillMax(1024,512).AbsoluteLink
$Image.AbsoluteLink
$Image.Link
```
Tried these settings, only the ones without FocusFillMax have links. The first one does not have a link at all.

**Comment by jonom** [comment]
Does `$Image.FillMax(1024,512).AbsoluteLink` work? If not, this would be an issue in the framework rather than this module.

**Comment by bummzack** [comment]
Seems like these are missing on `DBFile`. It might be on purpose… `AbsoluteURL` and `URL` always work though.

**Comment by bummzack** [comment]
Yeah… seems like `Link` was fixed, whereas `AbsoluteLink` is still missing: https://github.com/silverstripe/silverstripe-assets/pull/110

**Comment by hp7** [comment]
Could this be the same issue? 
$FeaturedImage.FocusScaleMaxWidth(610).Link 
won't output in template

**Comment by jonom** [comment]
@hp7 does `$FeaturedImage.FocusScaleMaxWidth(610).URL` work?

**Comment by hp7** [comment]
No, nothing is returning still

**Comment by jonom** [comment]
Just tested in SS4.4 and all of these work fine:

* $FocusFillMax(100, 100).Link
* $FocusFillMax(100, 100).URL
* $FocusFillMax(100, 100).AbsoluteLink
