### ISSUE TITLE
attach to file instead of image?

### ISSUE THREAD

**Issue by lekoala** [jonom/silverstripe-focuspoint#57]
Hey!

Just a quick question. I'm currently fighting in my projects to reduce the number of tables generated by silverstripe (simply to make dumps faster, etc)

Attaching the extension on the image create three new table Image, Image_Live and Image_Versions

Although it makes more sense to attach it to the image, do you think it could make sense to actually attach the extension to all files? Or at least have the fields generated in the File table to avoid these 3 tables from being generated?

**Comment by jonom** [comment]
_I_ wouldn't do that, and I wouldn't accept a PR to make that the default behaviour, but if you want to do that in your own projects I can't think of any reason off the top of my head that it shouldn't work :)
