### ISSUE TITLE
Call to a member function getX() on null

### ISSUE THREAD

**Issue by digitall-it** [jonom/silverstripe-focuspoint#58]
When trying to use this fantastic focuspoint plugin with Silverstripe 4.3 and Elemental 4, got this error, even if trying to edit images from the Files UI directly:
```
[2019-01-31 15:48:04] error-log.ERROR: Uncaught Exception Error: "Call to a member function getX() on null" at /var/www/html/vendor/jonom/focuspoint/src/Forms/FocusPointField.php line 91 {"exception":"[object] (Error(code: 0): Call to a member function getX() on null at /var/www/html/vendor/jonom/focuspoint/src/Forms/FocusPointField.php:91)"} []
```

![schermata 2019-01-31 alle 15 48 12](https://user-images.githubusercontent.com/3578378/52062037-07446b00-2570-11e9-8e72-d6ad402d54cd.png)

At first it seemed to work, then something bad happened. Tried to uninstall and reinstall it, `dev/build?flush=all`, `composer vendor-expose` and so on.

**Comment by digitall-it** [comment]
Trying to debug the problem with @lerni, we found out the culprit is the translations. To replicate the problem, just switch the CMS to italian.

The problem is that the fix (hardwire the FocusPoint string) makes the UI appear but it isn't usable. So the suggested course of action, for now, is simply to nuke all localizations while a proper workaround is found.

**Comment by jonom** [comment]
This appears to be the same issue as https://github.com/jonom/silverstripe-focuspoint/issues/65 and should be fixed with https://github.com/jonom/silverstripe-focuspoint/pull/74
