### ISSUE TITLE
FocusFill doesn't check wether owner exists

### ISSUE THREAD

**Issue by lerni** [jonom/silverstripe-focuspoint#59]
If an Image gets deleted but references still exists, FocusFill & FocusFillMax 'll error like: "Uncaught InvalidArgumentException: Width is required". A check like if ($this->owner->exists()) in FocusFill would prevent this. Would it be aceptable to just wrap the return in such a condition?

**Comment by lerni** [comment]
probable some more exist-checks are needed to fix https://github.com/jonom/silverstripe-focuspoint/issues/58

https://github.com/jonom/silverstripe-focuspoint/blob/master/src/FieldType/DBFocusPoint.php#L32
https://github.com/jonom/silverstripe-focuspoint/blob/master/src/Forms/FocusPointField.php#L83

**Comment by jonom** [comment]
Thanks @lerni. Any chance you would like to open a PR to fix this?

**Comment by lerni** [comment]
Yeah, with pleasure. So you think what I said is the right approach?

**Comment by jonom** [comment]
I think so, but maybe you could check what the behaviour is for built-in methods. Like if you call `Fill` instead of `FillMax` in the same situation does it fail silently or throw an error? Replicating the native behaviour for consistency is probably the best way to go.

**Comment by jonom** [comment]
Fixed with #63

**Comment by lerni** [comment]
thank you @mikenz, somehow just never made it.
