### ISSUE TITLE
Compatible with Silverstripe 4.4.1 - latest stable release?

### ISSUE THREAD

**Issue by neilcreagh** [jonom/silverstripe-focuspoint#60]
Just starting a new project with Silberstripe's latest stable release v4.4.1 but I think FocusPoint isn't compatible — it's crashing the file viewer/editor and I'm getting Error: Injector.get(): Component FocusPointField does not exist

I tried composer vendor-expose but no joy — any ideas for a quick fix?

**Comment by aletail** [comment]
I can confirm, seeing the same issue with v4.4.1. To reproduce:
- simply attempt to view any image in the file section

**Comment by RuthAdele** [comment]
Same issue over here.

**Comment by aNickzz** [comment]
Yea, whatever is going on is also affecting the file selector for upload fields;

I get this on CMS page load (not sure if its related)
```
main.js:1 Uncaught TypeError: Cannot read property 'string' of undefined
```
and this when selecting an image
```
vendor.js?m=1560140517:1 Error: Injector.get(): Component FocusPointField does not exist
```

**Comment by kinglozzer** [comment]
https://docs.silverstripe.org/en/4/changelogs/4.4.0/#upgrade-to-react-16-in-the-cms

Looks like this module will need to include the `prop-types` package manually from now on: https://www.npmjs.com/package/prop-types

**Comment by kinglozzer** [comment]
PR here: https://github.com/jonom/silverstripe-focuspoint/pull/61

**Comment by jonom** [comment]
Thanks all for the reports, and especially Loz for the fix!
