### ISSUE TITLE
Internal server error in asset-admin if file is missing

### ISSUE THREAD

**Issue by kinglozzer** [jonom/silverstripe-focuspoint#65]
If the underlying file for an image is missing, clicking the file in the assets admin section results in an internal server error:

> Call to a member function getWidth() on null

Which comes from here:

https://github.com/jonom/silverstripe-focuspoint/blob/16dedb9549e719bf5d1030eb84f664f7b7a69e8f/src/Forms/FocusPointField.php#L86-L90

I think we just need an `if ($previewImage)` check in there somewhere, I’m not sure what happens if you omit the `previewUrl`/previewWidth`/`previewHeight` schema items 😅

**Comment by jonom** [comment]
Hmm that sounds just like this issue: https://github.com/jonom/silverstripe-focuspoint/issues/59 are you running 3.1.1?

**Comment by kinglozzer** [comment]
Yeah I am on 3.1.1, #59 sounds similar but I think it’s a different cause

**Comment by jonom** [comment]
Fixed by https://github.com/jonom/silverstripe-focuspoint/pull/74 thanks @kinglozzer and @ohararyan!
