### ISSUE TITLE
Call to a member function getX() on null

### ISSUE THREAD

**Issue by banglashi** [jonom/silverstripe-focuspoint#76]
Hi @jonom,

first of all thanks for the great module.
I noticed a weird error wich I get in the cms when opening a single view of a file `Call to a member function getX() on null`. When you create the FocusPointField you pass in 3 parameters, $name, $title and $image. On the title you pass in $image->fieldLabel('FocusPoint') which translates to "Focus point".

https://github.com/jonom/silverstripe-focuspoint/blob/847f479747aa68e7d5fb1699b2f46bd4894cc792/src/Extensions/FocusPointAssetFormFactoryExtension.php#L25

Later you `$this->setName`
https://github.com/jonom/silverstripe-focuspoint/blob/847f479747aa68e7d5fb1699b2f46bd4894cc792/src/Forms/FocusPointField.php#L63
 and after you call `parent::__construct` passing $title and $fields.
https://github.com/jonom/silverstripe-focuspoint/blob/847f479747aa68e7d5fb1699b2f46bd4894cc792/src/Forms/FocusPointField.php#L64

Somehow the name doesn't get set properly (check how FieldGroup handles it) and later on getSchemaStateDefaults when you do `$this->getName()` it returns `Focuspoint` but it actually should return `FocusPoint`
https://github.com/jonom/silverstripe-focuspoint/blob/847f479747aa68e7d5fb1699b2f46bd4894cc792/src/Forms/FocusPointField.php#L91

That's why it gets a null reference and fails when trying to getX() on it. Let me know if you have any more questions.

Best regards

**Comment by jonom** [comment]
Can you try the dev-master branch? The same error was [reported previously](https://github.com/jonom/silverstripe-focuspoint/issues/65) and hopefully fixed, but it hasn't been released yet.

**Comment by banglashi** [comment]
dev-master works. Thanks.

**Comment by sb-relaxt-at** [comment]
From my understanding this issue is not resolved (using the latest 3.1.3 release). It only happens when the field label resolves to something different from "Focus Point". From my limited testing it should be sufficient if the parent constructor of FocusPointField is called prior setting name and value.
