### ISSUE TITLE
Make disabled state of picker more obvious

### ISSUE THREAD

**Issue by micschk** [jonom/silverstripe-focuspoint#99]
Not sure where else to put this but the picker 'seems' active when viewing an image in view-mode (form disabled). Clients try to alter the focus point but this doesn't change as it's disabled. Only after clicking the 'Details' button, the focuspoint can actually be altered.
<img width="87" alt="Screenshot 2021-09-10 at 15 56 06" src="https://user-images.githubusercontent.com/1005986/132864702-6c040dc9-d6b1-4da7-ab8f-74d2ca718822.png">

To make this more obvious, I'd proposte we grey-out & dim the image, just like the other disabled inputs of this form;
<img width="236" alt="Screenshot 2021-09-10 at 15 57 44" src="https://user-images.githubusercontent.com/1005986/132865002-15eaf015-c020-40a7-b321-468213d0c1ce.png"> <img width="270" alt="Screenshot 2021-09-10 at 15 55 41" src="https://user-images.githubusercontent.com/1005986/132864756-6823fc30-2103-4c32-9412-442a46968a79.png">

Achieved with some basic CSS:

```css
#Form_fileSelectForm .focuspoint-picker {
  filter: grayscale(100%);
  opacity: .6;
}
```

**Comment by jonom** [comment]
@micschk totally feel you on this, intended do something like this but never got around to it. This has been done now, tagged [4.0.1](https://github.com/jonom/silverstripe-focuspoint/releases/tag/4.0.1).

**Comment by micschk** [comment]
Great jonom, thx!
